// Copyright 2023 Im-Beast. MIT license.

import { defineShowcaseManifest } from "../../../src/showcase/mod.ts";
import type { InkstoneNoteFixture } from "./model.ts";

/** Versioned showcase metadata consumed by the shared launcher and test kit. */
export const INKSTONE_MANIFEST = defineShowcaseManifest({
  id: "inkstone",
  title: "Inkstone",
  appVersion: "0.1.0",
  routes: [
    { id: "vault", title: "Vault" },
    { id: "note", title: "Note" },
    { id: "search", title: "Search" },
    { id: "diagnostics", title: "Diagnostics" },
  ],
  initialRouteId: "vault",
  requiredCapabilities: ["vault.list", "vault.read", "vault.write"],
  optionalCapabilities: ["vault.optimistic-conflict", "vault.snapshot"],
  hosts: { terminal: true, browser: false },
});

/** Creates a fresh deterministic fixture set for each provider or test. */
export function createInkstoneFixtures(): InkstoneNoteFixture[] {
  return [
    {
      id: "welcome",
      path: "Welcome.md",
      revision: 1,
      updatedAt: 1_700_000_000_000,
      source: [
        "---",
        "title: Welcome to Inkstone",
        "tags: [start, knowledge-base]",
        "aliases: [Home, Start Here]",
        "status: active",
        "---",
        "",
        "# Welcome to Inkstone",
        "",
        "Inkstone keeps writing, navigation, and recovery in one deterministic workspace.",
        "",
        "## Tour",
        "",
        "Continue with [[Orbital|the orbital project]] or read [Unicode notes](Research/Unicode.md).",
        "The fixture also retains [[Missing Observatory]] as an unresolved-link diagnostic.",
        "",
        "- [x] Open the vault",
        "- [ ] Save a revision",
        "",
        "#welcome #demo",
      ].join("\n"),
    },
    {
      id: "orbital",
      path: "Projects/Orbital Command.md",
      revision: 2,
      updatedAt: 1_700_000_100_000,
      source: [
        "---",
        "title: Orbital Command",
        "tags:",
        "  - project",
        "  - telemetry",
        "aliases: [Orbital, Mission Control]",
        "status: in-progress",
        "---",
        "",
        "# Orbital Command",
        "",
        "A mission-control notebook linked back to [[Home]].",
        "",
        "## Telemetry plan",
        "",
        "The renderer notes live in [Unicode research](../Research/Unicode.md#grapheme-safety).",
        "",
        "```md",
        "[[Home]] and #not-a-tag are examples inside a fence, not live index entries.",
        "```",
        "",
        "## Next burn",
        "",
        "Validate the tracking window before T+42 minutes. #operations",
      ].join("\n"),
    },
    {
      id: "unicode",
      path: "Research/Unicode.md",
      revision: 3,
      updatedAt: 1_700_000_200_000,
      source: [
        "---",
        "title: Café 👩🏽‍💻 and Graphemes",
        "tags: [research, unicode]",
        "aliases:",
        "  - Unicode Notes",
        "  - Grapheme Lab",
        "status: evergreen",
        "---",
        "",
        "# Café 👩🏽‍💻 and Graphemes",
        "",
        "Text cells must preserve é, emoji modifiers, and full grapheme boundaries.",
        "",
        "## Grapheme safety",
        "",
        "Compare the editor with [[Workbench Design]] and return to [Welcome](../Welcome.md).",
        "",
        "## Width fixtures",
        "",
        "ASCII, Ελληνικά, 日本語, العربية, and emoji should remain searchable. #i18n",
      ].join("\n"),
    },
    {
      id: "workbench",
      path: "Design/Workbench.md",
      revision: 1,
      updatedAt: 1_700_000_300_000,
      source: [
        "---",
        "title: Workbench Design",
        "tags: [design, workbench]",
        "aliases: [Workbench Design]",
        "status: review",
        "---",
        "",
        "# Workbench Design",
        "",
        "The wide layout combines explorer, editor, preview, outline, backlinks, and diagnostics.",
        "",
        "## Responsive modes",
        "",
        "Compact mode keeps the same state while showing one pane at a time.",
        "See [[Unicode Notes]] and [[Orbital Command]].",
      ].join("\n"),
    },
    {
      id: "citations",
      path: "Reference/Citations.md",
      revision: 1,
      updatedAt: 1_700_000_400_000,
      source: [
        "---",
        "title: Citation Shelf",
        "tags: [reference]",
        "aliases: [Sources]",
        "status: active",
        "---",
        "",
        "# Citation Shelf",
        "",
        "A bounded fixture for bibliography and task-table follow-up work.",
        "",
        "## Reading queue",
        "",
        "- [ ] Unicode Standard Annex #29",
        "- [x] CommonMark reference",
        "",
        "Return to [[Start Here]].",
      ].join("\n"),
    },
  ];
}
