// Copyright 2023 Im-Beast. MIT license.

// GENERATED FILE — do not edit by hand.
// Regenerate with: deno run -A --unstable-webgpu -c packages/exomux/deno.json scripts/audit_butterchurn_gpu.ts
//
// The presets the GPU butterchurn background auto-cycles: those that render to a
// non-blank frame on the GPU. Of 472 presets in the catalog: 383 draw, 89 resolve to
// black/near-black on the GPU path and are skipped so auto-cycle does not strobe
// through them. Every preset stays selectable by index through
// `EXOMUX_BUTTERCHURN_CATALOG`; this only decides what the GPU field auto-cycles.

/** Names of the GPU-drawable presets, in catalog order. */
export const EXOMUX_BUTTERCHURN_GPU_ROTATION: readonly string[] = [
  "$$$ Royal - Mashup (157)",
  "$$$ Royal - Mashup (160)",
  "$$$ Royal - Mashup (220)",
  "$$$ Royal - Mashup (253)",
  "$$$ Royal - Mashup (273)",
  "$$$ Royal - Mashup (307)",
  "$$$ Royal - Mashup (337)",
  "$$$ Royal - Mashup (417)",
  "$$$ Royal - Mashup (431)",
  "$$$ Royal - Mashup (441)",
  "$$$ Royal - Mashup (489)",
  "11",
  "269",
  "27",
  "286",
  "444",
  "_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)",
  "_Eo.S. - glowsticks v2 02 - Geiss HPF",
  "_Flexi, martin + geiss - painterly rogue wave strike (color emboss mix)",
  "_Geiss - Artifact 01",
  "_Geiss - Brain Zoom 3 (Color Emboss Mix)",
  "_Geiss - Explosion Mod 2b",
  "_Geiss - untitled",
  "_geiss_experimental__wavefronts",
  "_Krash + Eo.S. - Photographic Sentinel",
  "_Mig_014_version2",
  "_Mig_049",
  "_Mig_079",
  "_Mig_085",
  "_Mig_COLORFUL9",
  "_Mig_Oscilloscope008",
  "_Vovan + Geiss - Bass With Flover (Feedback Mix) 2",
  "A Tribute to Martin - bombyx mori - Ft Flexi - AdamFX - StahlRegen - Krash - Rovastar -  Hd in Milk T",
  "adam eatit fx 2 martin - disco mix, lodus, geiss, ludicrous speed,flexi, aderrasi n hexcollie",
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed + Aderrasi 2_1",
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed + Baked Ft another AdamFX Mashup 7_1",
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed + Eos Ft Flexi n Hexocollie + Baked + Santa Fucking Claus",
  "AdamFx 2 Aderrasi - Airhandler (Last Breath - Calm)Ilusional Discontent2",
  "AdamFx 2 Geiss, Zylot and Flexi - Reaction Diffusion 3 (Overload Mix 2) EATIT4 hypno",
  "AdamFX Enterz Tha Mash With Martin + stahlregen - AdamFX - In Tha Mash Effectz E",
  "AdamFX Mashup 2 Martin - reflections on black tile + Raron N Flexi ",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Painterly Tendrils Colorfast",
  "Aderrasi + Geiss - Airhandler (Square Mix)",
  "Aderrasi - Agitator",
  "Aderrasi - Airhandler (Last Breath - Calm)",
  "Aderrasi - Airhandler (Principle of Sharing)",
  "Aderrasi - Curse of the Mirror Emu",
  "Aderrasi - Halls Of Centrifuge",
  "Aderrasi - Potion of Spirits",
  "Aderrasi - Songflower (Moss Posy)",
  "Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics",
  "Aderrasi - Veil of Steel (Steel Storm) - mash0000 - bob ross finally loses it",
  "afro-legionican",
  "amandio c - feeling well 3",
  "amandio c - flashy thing",
  "amandio c - salty beats - spiral",
  "amandio c - salty bits - 5 nz+ jealiousea",
  "An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B",
  "baked - Chinese Fingerbang (cao ni ma =]) - PieturP colors - Bitcore speed tweak",
  "baked - mushroom rainbows[acid Storm]",
  "baked - River of Illusion Dillusion [Bubble]",
  "bdrv + al shifter - feathers (angel wings)_phat_remix4 bdrv et  AL  rmxmix bdrv et.AL5",
  "bdrv - ultramix2 #43",
  "beta106i - Brilliance (Space-Time Breaking) - mash0000 - it′s 2009 and you haven′t replaced your analog tv with digital",
  "beta106i - Inhuman Emotion (Regret) - mash0000 - genetic mutant incubators in the hands of toddlers",
  "beta106i - Potion of Ink",
  "cope + flexi - colorful marble (ghost mix)",
  "cope + flexi - mother-of-whirl [no fnords were hurt]",
  "cope + geiss + stahlregen - cartune (bending gelatine mix)",
  "cope + martin - mother-of-pearl",
  "cope - alternative energy (antimatter mod_1)4z",
  "cope - digital sea",
  "Cope - Passage (mandala mix)",
  "cope - strange attractor [flexis let it grow mix] (Jelly 5.56 [volume noise zoom-in])",
  "cope - the drain to heaven",
  "Cope - The Neverending Explosion of Red Liquid Fire",
  "cope, martin + flexi - the slickery of alternative varnish",
  "DemonLD_-_Toxic_water_diffusion threx angela vs debi brown (nice)",
  "ech0 - liquid firesticks I",
  "Eo.S. + flexi - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b + illumination (Stahl′s Mix)",
  "Eo.S. + Geiss - glowsticks v2 02 (Relief Mix)",
  "Eo.S. + Phat - cubetrace - v2",
  "Eo.S. + Phat - Emergent factors",
  "Eo.S. + Zylot - skylight (Stained Glass Majesty mix)",
  "Eo.S. - glowsticks v2 03 music",
  "Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b",
  "Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix07 recursive demons",
  "Eo.S. - multisphere 01 B_Phat_Ra_mix",
  "Eo.S. - spark C_Phat_Jester_Mix_v2",
  "EoS_Phat Dark_heart_nobal_cause cpe ap4+",
  "ethical rotterdamasm",
  "EVET - RGB Singularity",
  "fed + flexi + geiss - tokamak repellor tech twist mix [stabilized]",
  "fed + flexi - tech test 2-1 - humpgorge",
  "fed - glowing 5 - fingers rmx nz+ round squarishness",
  "fed - slowfast 1.1",
  "fishbrain + flexi - stitchcraft",
  "fiShbRaiN + Flexi - witchcraft 2.0",
  "fiShbRaiN + flexi - witchcraft 2.0 - mash0000 - no one cares about mi, the note (major third)",
  "fiShbRaiN + geiss - witchcraft (Grow Mix 3)",
  "fiShbRaiN - a quiet death",
  "fiShbRaiN - the adventures of prismo jenkins",
  "fiShbRaiN - toffee cream and icing sugar",
  "fiShbRaiN, flexi + martin - grafitti tagging witchcraft must be overrated - demonlord shaders - lampshade hubrys2",
  "flexi + amandio c - organic",
  "flexi + amandio c - organic [random mashup]",
  "flexi + amandio c - organic12-3d-2.milk",
  "Flexi + amandio c - piercing 05 - Kopie (2) - Kopie",
  "flexi + fishbrain - neon mindblob grafitti",
  "Flexi + fiShbRaiN - operation fatcap II",
  "flexi + fishbrain - witchcraft [complex terraforming - fiddling twists in the fabric of space]",
  "flexi + fishbrain - witchcraft [complex terraforming]",
  "Flexi + Geiss + Demon Lord - unholy tokamak clot-plot",
  "flexi + geiss - infused with the spiral (Heavy Oil Mix) nz+ rapery",
  "Flexi + Geiss - pogo-cubes on tokamak matter (Jelly 5.55)",
  "flexi + geiss - pogo-cubes on tokamak matter [mind over matter remix]2",
  "Flexi + Geiss - Tokamak mindblob 2.0",
  "Flexi + Martin - astral projection",
  "Flexi + Martin - cascading decay swing",
  "Flexi + Martin - tunnel of supraschismatika",
  "flexi + nitorami - beat explorer (cn bc jelly 4)",
  "Flexi + Rovastar - Fractopia [lovecraft]",
  "Flexi + stahlregen - jelly showoff parade",
  "flexi + stahlregen - jelly strike",
  "flexi - alien canvas [learning]",
  "Flexi - alien fader",
  "Flexi - alien fish pond",
  "Flexi - alien web bouncer [26]",
  "Flexi - blame hexcollie twice",
  "flexi - borderline imagery",
  "flexi - bouncing balls [double mindblob gastrointestinal mix]",
  "flexi - bouncing balls [double mindblob neon mix]",
  "flexi - bouncing balls [illumination mix]",
  "flexi - bouncing balls [mindblob terraforming] flx roams domikleasing undergraeduhate",
  "flexi - color strike",
  "Flexi - crush ice 72",
  "Flexi - dimensions, projection and abstraction",
  "flexi - grind my glitch up [190]",
  "flexi - hyperspaceflight (bn cn Jelly 4)",
  "Flexi - infused with the spiral",
  "flexi - infused with the spiral (jelly 4.x cn)",
  "flexi - inter state",
  "flexi - jelly fish mandala",
  "flexi - meta4free",
  "flexi - Mindblob",
  "Flexi - mindblob 2.0",
  "Flexi - mindblob [shiny mix]",
  "Flexi - mindblob mix",
  "flexi - mom, why the sky looks different today",
  "flexi - patternton, district of media, capitol of the united abstractions of fractopia",
  "Flexi - piercing",
  "Flexi - predator-prey-spirals",
  "Flexi - predator-prey-spirals [stahlregens gelatine finish]",
  "Flexi - reality tunnel",
  "Flexi - smashing fractals 2.0",
  "Flexi - smashing fractals [acid etching mix]",
  "flexi - splatter effects 17 the wave, a google love story written in decay roam3-2 ",
  "Flexi - the distant point between derivative",
  "flexi - what is the matrix",
  "Flexi - wild at range",
  "Flexi, fishbrain + Martin - witchery",
  "Flexi, fishbrain, Geiss + Martin - tokamak witchery",
  "flexi, geiss and rovastar - chaos layered sinewsed tokamak 2",
  "Flexi, Geiss and Rovastar - chaos layered tokamak",
  "Flexi, martin + geiss - dedicated to the sherwin maxawow",
  "Flexi, martin + geiss - painterly rogue wave strike",
  "Flexi, Martin, Phat, Zylot + Eo.S - one way trip trap proof of concept [epileptic zoom tunnel edit]",
  "Flexi, Rovastar + Geiss - Fractopia vs bas relief",
  "flexi, stahlregen, geiss + tobias wolfboi - space gelatine burst - mash0000 - chromatidal pool mirror blasphemy",
  "Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b",
  "Fumbling_Foo + En D & Martin - Mandelverse",
  "Geiss + Flexi + Martin - disconnected",
  "Geiss + Rovastar - Notions Of Tonality 2",
  "Geiss - 3 layers (Tunnel Mix)",
  "Geiss - Brain Zoom 4",
  "Geiss - Color Pox (Acid Impression Mix) (color saturation remix)",
  "Geiss - Desert Rose 4",
  "Geiss - Explosion Mod 2bd (wave)",
  "Geiss - Feedback 2",
  "Geiss - Game of Life 3",
  "Geiss - Myriad Mosaics",
  "Geiss - Reaction Diffusion (Puddle Mix)s a aa aa",
  "Geiss - Reaction Diffusion (Relief Mix)",
  "Geiss - Reaction Diffusion 2",
  "Geiss - Reaction Diffusion 3",
  "Geiss - Reaction Diffusion 3 (Lichen Mix)",
  "Geiss - Skin Dots 9",
  "Geiss - Skin Dots Multi-layer 3",
  "Geiss - Spiral Artifact",
  "Geiss - Thumb Drum",
  "Geiss - Tokamak Plus 2",
  "Geiss - Two-Pointed Pulsagon - mash0000 - bubonic super-fluid centrifuge",
  "Goody + flexi - Data Crusher",
  "goody + martin - crystal palace - schizotoxin - the wild iris bloom - 16 iterations",
  "GreatWho - Lasershow",
  "gunthry is out back bloodying up the pine trees - adm atomising (v) the disintigrate (n)",
  "Halfbreak - Funny Madness",
  "Halfbreak - Light of Breakers",
  "Hexcollie - Nautalisk - mash0000 - but officer, my fingerprint always changes",
  "Hexcollie, Pieturp, Orb, Flexi, Geiss n Demon Lord - Premeditative Urination Clause",
  "high-altitude basket unraveling - singh grooves nitrogen argon nz+",
  "Idiot - Marphets Surreal Dream (Hypnotic Spiral Mix)",
  "iMuS and  Rovastar - The Shroomery (psilobellum)",
  "Isosceles mashup07",
  "it is the night of the demon weed bowel",
  "Krash & Rovastar - A Million Miles from Earth (Ripple Mix)",
  "Krash + Illusion + Geiss - Spiral Movement (Reaction Diffusion mix)",
  "Krash + Illusion - Spiral Movement",
  "LuxXx - GrindFace  225 mg dose  ",
  "LuxXx - iWhat Happened Right After I Ate That Toxic Waste beta ii",
  "LuxXx - Play v3 (the war within all of us)",
  "LuxXx - Subtle HipHopFlake",
  "martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained",
  "martin + stahlregen - martin in da mash 12",
  "martin + stahlregen - martin in da mash 12a",
  "martin + stahlregen - martin in da mash 14",
  "martin + stahlregen - martin in da mash 3",
  "Martin - acid wiring",
  "martin - amandio c - a different view of the green machine",
  "martin - angel flight",
  "martin - another kind of groove",
  "martin - baby one more time",
  "martin - bombyx mori",
  "martin - bombyx mori [flexi′s logarithmic edit]",
  "Martin - bombyx mori mix2",
  "martin - bring up the big guns",
  "martin - carpet weaver",
  "martin - castle in the air",
  "martin - chain breaker",
  "Martin - charisma",
  "martin - cherry brain wall mod",
  "martin - city of shadows",
  "Martin - cool morning",
  "martin - crystal alley",
  "Martin - Diabolo",
  "Martin - disco mix 6",
  "martin - elusive impressions mix2 - flacc mess proph nz+2",
  "martin - extreme heat",
  "martin - Flexis swarm in Martins pond [not yet a boid implementation] ",
  "martin - fruit machine",
  "martin - gate to moria",
  "martin - ghost city",
  "martin - glass corridor",
  "martin - glass corridor nz2 incline",
  "martin - glassball dance",
  "martin - into the fireworks",
  "Martin - journey into space",
  "Martin - liquid arrows",
  "martin - ludicrous speed",
  "martin - mandelbox explorer - high speed demo version",
  "martin - move this body",
  "martin - mucus cervix",
  "martin - neon space ps2 (ati fix) - yaqui graph - flx food",
  "Martin - QBikal - Surface Turbulence IIb",
  "martin - reflections on black tiles",
  "martin - resonant twister - steel spring",
  "martin - rogue wave -ps3",
  "martin - satellite view",
  "martin - shifter - armorial bearings of robotopia",
  "martin - skywards",
  "martin - soma in pink",
  "martin - sparky caleidoscope",
  "martin - starfield sectors",
  "martin - stormy sea (2010 update)",
  "martin - sunset over the river",
  "martin - The Bridge of Khazad-Dum",
  "martin - the bridge of khazad-dum [flexi's growth raised to the power of transcendence mix]",
  "martin - the forge of Isengard",
  "martin - tunnel race",
  "martin - unholy amulet 2",
  "martin - violet flash",
  "martin - witchcraft reloaded",
  "martin [shadow harlequins shape code] - fata morgana",
  "Martin N AdamFX Infusion = Phat+Yin+Eo.S_Mandala Chaser Ft AdamFX n Martin - The Beast Mandala Chaser FX H",
  "martin, fishbrain + flexi - mandelbox explorer v1 Eo.S. optimize [bipolar witchcraft mix]",
  "martin, flexi, fishbrain + sto - enterstate [random mashup]",
  "Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX",
  "MilkDrop2077.R002",
  "MilkDrop2077.R012",
  "MilkDrop2077.R033",
  "MilkDrop2077.R037",
  "never suggest things roam glance at sun for galactic upgrade",
  "NeW Adam Master Mashup FX 2 Geiss - Reaction Diffusion 34 + Swelling Spiral  + Liquid Fire  + Geiss an46",
  "NeW Adam Master Mashup FX 2 Geiss and Zylot - Reaction Diffusion 3 (Overload Mix 2) AMAZING MASUP Various + Hurricane Nightmare",
  "one-sided infinite-dimensional shape - helenisch",
  "orb - acid cycle [flexi shader mix] - yaqui graph",
  "ORB - Blue Emotion",
  "ORB - Depth Charge 2",
  "ORB - Fire and Fumes 2",
  "ORB - Planetary Alignment Acid Burn",
  "orb - toxic goo",
  "ORB - Waaa",
  "phat + Eo.S. - Bass_responce_Red_Movements_Disorienting nebula3",
  "Phat + Zylot + Eo.S. - work with lines",
  "Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix",
  "Phat_Zylot_Eo.S. spiral_Movements_Beatle",
  "Phat_Zylot_Eo.S. square_faces_v2_alt_colours",
  "PieturP - triptrap_(getting_concrete_visions_through_a_diafragma_version)",
  "PieturP - triptrap_(ultimate-trip-mix)",
  "raron - a grayish blob - mash0000 - pungent gastric automata cloud fumes",
  "rce-ordinary + flexi - far away distance (custom beat detection + bipolar colour ghost mix)",
  "Redi Jedi - i dont think those were portabello mushrooms",
  "repressed americans - massive cheese lard nz+ redkneck treads",
  "Rocke - Answer.42 (New Mix 1) - mash0000 - slash and char p. jungle",
  "Rovastar & Idiot24-7 - Balk Acid",
  "Rovastar & Loadus + Zylot - FractalDrop (Spark Machine v2.0)",
  "Rovastar + Che - Asylum Animations",
  "Rovastar + Fvese - Mosaic Waves",
  "Rovastar + Geiss - Hurricane Nightmare (Relief Mix)",
  "Rovastar + Geiss - Hyperspace - kaleidoscope",
  "Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)",
  "Rovastar + Loadus + Geiss - Tone-mapped FractalDrop 7c",
  "Rovastar + Telek - Altars of Madness (Rolling Oceans Mix)",
  "Rovastar - A Million Miles From Earth (Wormhole Mix)",
  "Rovastar - Harlequin′s Fractal Encounter - cancer of saints",
  "Rovastar - Oozing Resistance",
  "Rovastar - Torrid Tales",
  "Rovastar-altarsofmadness(forgottenrea",
  "Rozzor & Shreyas - Deeper Aesthetics",
  "sawtooth grin roam",
  "ShadowHarlequin - LovelyShinySquares [ liquid starburst rmx ] - unchained + rovaster - luckless - martin - starfield sector",
  "shifter + flexi - american oblivion pie",
  "shifter - dark tides bdrv mix",
  "shifter - dark tides bdrv mix 2",
  "shifter - escape (sigur ros)",
  "shifter - escape the worm - Eo.S. + Phat - Before_It_Eats_Your_Brain_Mix_v2",
  "shifter - feathers (angel wings)",
  "shifter - feathers (angel wings)_phat_remix relief 2",
  "shifter - fire and brimstone",
  "shifter - fractal grinder",
  "shifter - fuzzball 3d (glasses) false auralary2 undre thee bottom qoaguluste",
  "shifter - liquid circuitry - conjugoth",
  "shut down all survival paradigms",
  "Stahlregen & Boz - Machine Code (Reaction Diffusion)_1 - Isosceles Tweak 08",
  "Stahlregen & flexi + Geiss + Rovastar + Shifter - Fractal Feedback (for Hexcollie)",
  "stahlregen & geiss + rovastar - fields of flowers (mashup 9 - space flower rmx) - mash0001 - pack em in, we got a long haul + flashlight",
  "stahlregen + geiss + shifter - babylon",
  "Stahlregen + martin + others - Psychedelic Metal Flower",
  "stahlregen - dots (layered) - suksma world humanvirus replication killphreqs mix",
  "Stahlregen - Dots (Pixels - Blocky) (Jelly V2)",
  "stahlregen - old school, baby (spiral ornament)",
  "Studio Music and Unchained - Rapid Alteration",
  "suksma - barium titanate",
  "suksma - coal drapes - mrt fsh gordo dog crap in my bed cuz i sleep wid my shoes on",
  "suksma - ed geining hateops - flx i want you, i'm sick with you",
  "suksma - ed geining hateops - squeakers",
  "suksma - grainery clock mortis",
  "suksma - heretical crosscut playpen",
  "suksma - nip tuck",
  "suksma - pus on my cat - j4+ - cubby",
  "suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression",
  "suksma - uninitialized variabowl (hydroponic chronic)",
  "suksma - vector exp 1 - couldn′t not",
  "suksma - water cooled red uranium vs dotes - freeenergynow.net",
  "TEcHNO & SandStorm - Psychodelic Highway",
  "Telek - City Helix Lattice",
  "Telek - Sine Wave",
  "The NG + Flexi + BDRV - Ultramix, Aderrasi + Flexi - Predator Prey Spirals, Flexi - Jellyfish Jam",
  "TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-go-round + techstyle]",
  "TonyMilkdrop - Magellan's Nebula [Flexi - fancy + $this shall not retain]",
  "TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse]",
  "Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)",
  "Unchained - All You Can Eat",
  "Unchained - Fuzzy Sciences",
  "Unchained - Making a Science of It 4",
  "Unchained - Making a Science of It 7",
  "Unchained - Rewop",
  "Unchained - Unified Drag 2",
  "undulate harque - shit broo",
  "va ultramix - 154 [chaos]",
  "various artists - 1200774354134 - mash0000 - what the writer′s guild is doing with the extra money",
  "Waltra - Heaven Liquid",
  "Waltra - Ice Plasma",
  "Waltra - Square Orgy",
  "yin - 190 - Temporal fluctuations",
  "yin - 253 - Artificial poles of the continuum (remix #3)",
  "yin - 315 - Ocean of Light (yo im peakin yo Eo.S.-Phat)",
  "yin - 352 - Chromatron (warped)",
  "yin - 393 - Artificial Inspiration (music driven - outward)",
  "Zylot - Crossing Over (Paint Spatter mix)",
  "Zylot - Star Ornament",
  "Zylot - True Visionary (Final Mix)",
];
