// Copyright 2023 Im-Beast. MIT license.

// GENERATED FILE — do not edit by hand.
// Regenerate with: deno run -A -c packages/exomux/deno.json scripts/audit_butterchurn_catalog.ts
//
// The presets the SOFTWARE-only butterchurn background ("butterchurn cpu")
// cycles through, chosen by rendering each on the CPU renderer and keeping those
// that resolve to a moving image at terminal resolution. Of 472 presets in the
// catalog: 365 ok, 83 blank, 16 saturated, 8 static.
//
// The excluded ones are not broken — most draw with custom waves, custom shapes
// and a composite shader, none of which the CPU renderer runs, so they resolve
// to an empty screen there (the GPU background renders them from their shaders).
// Every preset remains selectable by index through `EXOMUX_BUTTERCHURN_CATALOG`;
// this list only decides what the software field auto-cycles.

/** Names of the CPU-drawable presets, in catalog order. */
export const EXOMUX_BUTTERCHURN_ROTATION: readonly string[] = [
  "$$$ Royal - Mashup (157)",
  "$$$ Royal - Mashup (160)",
  "$$$ Royal - Mashup (177)",
  "$$$ Royal - Mashup (197)",
  "$$$ Royal - Mashup (220)",
  "$$$ Royal - Mashup (253)",
  "$$$ Royal - Mashup (273)",
  "$$$ Royal - Mashup (307)",
  "$$$ Royal - Mashup (326)",
  "$$$ Royal - Mashup (417)",
  "$$$ Royal - Mashup (431)",
  "$$$ Royal - Mashup (489)",
  "11",
  "269",
  "27",
  "286",
  "_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)",
  "_Eo.S. - glowsticks v2 02 - Geiss HPF",
  "_Flexi, martin + geiss - painterly rogue wave strike (color emboss mix)",
  "_Geiss - Artifact 01",
  "_Geiss - Brain Zoom 3 (Color Emboss Mix)",
  "_Geiss - Desert Rose 2",
  "_Geiss - Explosion Mod 2b",
  "_Geiss - untitled",
  "_geiss_experimental__wavefronts",
  "_Krash + Eo.S. - Photographic Sentinel",
  "_Mig_004_version2",
  "_Mig_009",
  "_Mig_028",
  "_Mig_049",
  "_Mig_056",
  "_Mig_079",
  "_Mig_085",
  "_Mig_COLORFUL9",
  "_Mig_Oscilloscope008",
  "_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)",
  "_Vovan + Geiss - Bass With Flover (Feedback Mix) 2",
  "A Tribute to Martin - bombyx mori - Ft Flexi - AdamFX - StahlRegen - Krash - Rovastar -  Hd in Milk T",
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed + Aderrasi 2_1",
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed + Baked Ft another AdamFX Mashup 7_1",
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed + Eos Ft Flexi n Hexocollie + Baked + Santa Fucking Claus",
  "AdamFx 2 Aderrasi - Airhandler (Last Breath - Calm)Ilusional Discontent2",
  "AdamFx 2 Geiss -Somewhat Distort Me 3_1",
  "AdamFX Mashup 2 Martin - reflections on black tile + Raron N Flexi ",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix",
  "Aderrasi + Geiss - Airhandler (Kali Mix) - Painterly Tendrils Colorfast",
  "Aderrasi + Geiss - Airhandler (Square Mix)",
  "Aderrasi - Agitator",
  "Aderrasi - Airhandler (Last Breath - Calm)",
  "Aderrasi - Airhandler (Principle of Sharing)",
  "Aderrasi - Contortion (Escher′s Tunnel Mix)",
  "Aderrasi - Contortion (Wide Twist Mix)",
  "Aderrasi - Curse of the Mirror Emu",
  "Aderrasi - Graft (First Rate Heart)",
  "Aderrasi - Halls Of Centrifuge",
  "Aderrasi - Mother Of Pearl - mash0000 - how to piss off your eyes",
  "Aderrasi - Potion of Spirits",
  "Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics",
  "Aderrasi - Veil of Steel (Steel Storm) - mash0000 - bob ross finally loses it",
  "afro-legionican",
  "amandio c - salty beats - spiral",
  "amandio c - salty bits - 5 nz+ jealiousea",
  "An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B",
  "baked - Chinese Fingerbang (cao ni ma =]) - PieturP colors - Bitcore speed tweak",
  "baked - mushroom rainbows[acid Storm]",
  "baked - River of Illusion Dillusion [Bubble]",
  "bdrv + al shifter - feathers (angel wings)_phat_remix4 bdrv et  AL  rmxmix bdrv et.AL5",
  "beta106at shape - mash0000 - hulk spirit cum",
  "beta106i - Brilliance (Space-Time Breaking) - mash0000 - it′s 2009 and you haven′t replaced your analog tv with digital",
  "beta106i - Burning Form (Seething Mass) - mash0000 - fire paint easter egg internals",
  "beta106i - Potion of Ink",
  "cope + flexi - colorful marble (ghost mix)",
  "cope + flexi - mother-of-whirl [no fnords were hurt]",
  "cope + geiss + stahlregen - cartune (bending gelatine mix)",
  "cope + martin - mother-of-pearl",
  "cope - alternative energy (antimatter mod_1)4z",
  "cope - digital sea",
  "Cope - Passage (mandala mix)",
  "cope - strange attractor [flexis let it grow mix] (Jelly 5.56 [volume noise zoom-in])",
  "cope - the drain to heaven",
  "Cope - The Neverending Explosion of Red Liquid Fire",
  "cope, martin + flexi - the slickery of alternative varnish",
  "ech0 - liquid firesticks I",
  "Eo.S. + flexi - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b + illumination (Stahl′s Mix)",
  "Eo.S. + Geiss - glowsticks v2 02 (Relief Mix)",
  "Eo.S. + Phat - cubetrace - v2",
  "Eo.S. + Phat cubetrace (cybercity madness remix) - mash0000 - evaporating crystal pharma",
  "Eo.S. + Zylot - skylight (Stained Glass Majesty mix)",
  "Eo.S. - glowsticks v2 03 music",
  "Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b",
  "Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix07 recursive demons",
  "Eo.S. - multisphere 01 B_Phat_Ra_mix",
  "Eo.S. - spark C_Phat_Jester_Mix_v2",
  "EoS - particle storm B - couldn't not",
  "EoS_Phat Dark_heart_nobal_cause cpe ap4+",
  "EVET - RGB Singularity",
  "fed + flexi + geiss - tokamak repellor tech twist mix [stabilized]",
  "fed - glowing 5 - fingers rmx nz+ round squarishness",
  "fed - slowfast 1.1",
  "fishbrain + flexi - stitchcraft",
  "fiShbRaiN + Flexi - witchcraft 2.0",
  "fiShbRaiN + flexi - witchcraft 2.0 - mash0000 - no one cares about mi, the note (major third)",
  "fiShbRaiN + geiss - witchcraft (Grow Mix 3)",
  "fiShbRaiN - breakfast cruiser",
  "fiShbRaiN - the adventures of prismo jenkins",
  "fiShbRaiN - toffee cream and icing sugar",
  "fiShbRaiN - witchcraft (necromancer remix)_phat_edit_v3",
  "fiShbRaiN, flexi + martin - grafitti tagging witchcraft must be overrated - demonlord shaders - lampshade hubrys2",
  "flexi + amandio c - organic",
  "flexi + amandio c - organic [random mashup]",
  "flexi + fishbrain - neon mindblob grafitti",
  "Flexi + fiShbRaiN - operation fatcap II",
  "flexi + fishbrain - warpcraft [random mashup]",
  "flexi + fishbrain - witchcraft [complex terraforming - fiddling twists in the fabric of space]",
  "flexi + fishbrain - witchcraft [complex terraforming]",
  "Flexi + Geiss + Demon Lord - unholy tokamak clot-plot",
  "flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]",
  "flexi + geiss - pogo-cubes on tokamak matter (bccn Jelly V4)",
  "Flexi + Geiss - pogo-cubes on tokamak matter (Jelly 5.55)",
  "flexi + geiss - pogo-cubes on tokamak matter [mind over matter remix]2",
  "Flexi + Geiss - Tokamak mindblob 2.0",
  "Flexi + Martin - astral projection",
  "Flexi + Martin - cascading decay swing",
  "Flexi + Martin - dive",
  "Flexi + Martin - tunnel of supraschismatika",
  "flexi + nitorami - beat explorer (cn bc jelly 4)",
  "Flexi + Rovastar - Fractopia [lovecraft]",
  "Flexi + stahlregen - jelly showoff parade",
  "flexi + stahlregen - jelly strike",
  "flexi - alien canvas [learning]",
  "Flexi - alien fish pond",
  "Flexi - alien web bouncer [26]",
  "flexi - bouncing balls [double mindblob gastrointestinal mix]",
  "flexi - bouncing balls [double mindblob neon mix]",
  "flexi - bouncing balls [illumination mix]",
  "flexi - bouncing balls [mindblob terraforming] flx roams domikleasing undergraeduhate",
  "flexi - color strike",
  "Flexi - dimensions, projection and abstraction",
  "flexi - hyperspaceflight (bn cn Jelly 4)",
  "Flexi - infused with the spiral",
  "flexi - infused with the spiral (jelly 4.x cn)",
  "flexi - jelly fish mandala",
  "flexi - meta4free",
  "Flexi - mindblob [shiny mix]",
  "flexi - patternton, district of media, capitol of the united abstractions of fractopia",
  "Flexi - predator-prey-spirals",
  "Flexi - predator-prey-spirals [stahlregens gelatine finish]",
  "Flexi - psychenapping",
  "Flexi - reality tunnel",
  "flexi - splatter effects 17 the wave, a google love story written in decay roam3-2 ",
  "flexi - swing out on the spiral",
  "Flexi - the distant point between derivative",
  "flexi - what is the matrix",
  "Flexi - wild at range",
  "Flexi, fishbrain + Martin - witchery",
  "Flexi, fishbrain, Geiss + Martin - tokamak witchery",
  "flexi, geiss and rovastar - chaos layered sinewsed tokamak 2",
  "Flexi, martin + geiss - dedicated to the sherwin maxawow",
  "Flexi, martin + geiss - painterly rogue wave strike",
  "Flexi, Rovastar + Geiss - Fractopia vs bas relief",
  "Fumbling_Foo + En D & Martin - Mandelverse",
  "Geiss + Flexi + Martin - disconnected",
  "Geiss + Rovastar - Notions Of Tonality 2",
  "Geiss - 3 layers (Tunnel Mix)",
  "Geiss - Brain Zoom 4",
  "Geiss - Cauldron - painterly (saturation remix)",
  "Geiss - Cauldron - painterly 2 (saturation remix)",
  "Geiss - Desert Rose 4",
  "Geiss - Eggs",
  "Geiss - El Cubismo",
  "Geiss - Explosion Mod 2bd (wave)",
  "Geiss - Feedback 2",
  "Geiss - Game of Life 3",
  "Geiss - Myriad Mosaics",
  "Geiss - Planet 1",
  "Geiss - Reaction Diffusion (Puddle Mix)s a aa aa",
  "Geiss - Reaction Diffusion (Relief Mix)",
  "Geiss - Reaction Diffusion 2",
  "Geiss - Reaction Diffusion 3",
  "Geiss - Reaction Diffusion 3 (Lichen Mix)",
  "Geiss - Skin Dots 9",
  "Geiss - Skin Dots Multi-layer 3",
  "Geiss - Tokamak Plus 2",
  "Geiss - Two-Pointed Pulsagon - mash0000 - bubonic super-fluid centrifuge",
  "Goody + flexi - Data Crusher",
  "Goody - Ego Decontructor",
  "Goody - The Wild Vort",
  "GreatWho - Lasershow",
  "gunthry is out back bloodying up the pine trees - adm atomising (v) the disintigrate (n)",
  "Halfbreak - Funny Madness",
  "Halfbreak - Light of Breakers",
  "Hexcollie - Cell division",
  "Hexcollie - Nautalisk - mash0000 - but officer, my fingerprint always changes",
  "Hexcollie, Pieturp, Orb, Flexi, Geiss n Demon Lord - Premeditative Urination Clause",
  "high-altitude basket unraveling - singh grooves nitrogen argon nz+",
  "Idiot - Star Of Annon",
  "Illusion & Rovastar - Dotty Mad Space (Jelly)",
  "iMuS and  Rovastar - The Shroomery (psilobellum)",
  "Ishan - Anuera",
  "Isosceles mashup07",
  "it is the night of the demon weed bowel",
  "Krash & Rovastar - A Million Miles from Earth (Ripple Mix)",
  "Krash + Illusion + Geiss - Spiral Movement (Reaction Diffusion mix)",
  "Krash + Illusion - Spiral Movement",
  "Krash - War Machine (Shifting Complexity Mix)",
  "LuxXx - Fuck Your Code ii",
  "LuxXx - GrindFace  225 mg dose  ",
  "LuxXx - iWhat Happened Right After I Ate That Toxic Waste beta ii",
  "LuxXx - Play v3 (the war within all of us)",
  "LuxXx - Subtle HipHopFlake",
  "martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained",
  "martin + stahlregen - martin in da mash 12",
  "martin + stahlregen - martin in da mash 12a",
  "Martin - acid wiring",
  "martin - amandio c - a different view of the green machine",
  "martin - angel flight",
  "martin - another kind of groove",
  "martin - baby one more time",
  "martin - bombyx mori",
  "martin - bombyx mori [flexi′s logarithmic edit]",
  "Martin - bombyx mori mix2",
  "martin - bring up the big guns",
  "martin - chain breaker",
  "Martin - charisma",
  "martin - cherry brain wall mod",
  "Martin - cool morning",
  "Martin - disco mix 3 -fast",
  "Martin - disco mix 6",
  "martin - elusive impressions mix2 - flacc mess proph nz+2",
  "martin - glass corridor",
  "martin - glass corridor nz2 incline",
  "martin - glassball dance",
  "martin - infinity (2010 update)",
  "martin - into the fireworks",
  "Martin - journey into space",
  "martin - ludicrous speed",
  "martin - move this body",
  "martin - mucus cervix",
  "martin - neon space ps2 (ati fix) - yaqui graph - flx food",
  "Martin - QBikal - Surface Turbulence IIb",
  "martin - reflections on black tiles",
  "martin - skywards",
  "martin - soma in pink",
  "martin - sparky caleidoscope",
  "martin - starfield sectors",
  "martin - The Bridge of Khazad-Dum",
  "martin - the bridge of khazad-dum [flexi's growth raised to the power of transcendence mix]",
  "martin - the forge of Isengard",
  "martin - unholy amulet 2",
  "martin - witchcraft reloaded",
  "martin [shadow harlequins shape code] - fata morgana",
  "Martin N AdamFX Infusion = Phat+Yin+Eo.S_Mandala Chaser Ft AdamFX n Martin - The Beast Mandala Chaser FX H",
  "martin, fishbrain + flexi - mandelbox explorer v1 Eo.S. optimize [bipolar witchcraft mix]",
  "martin, flexi, fishbrain + sto - enterstate [random mashup]",
  "Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX",
  "MilkDrop2077.R002",
  "MilkDrop2077.R012",
  "MilkDrop2077.R037",
  "never suggest things roam glance at sun for galactic upgrade",
  "NeW Adam Master Mashup FX 2 Geiss - Reaction Diffusion 34 + Swelling Spiral  + Liquid Fire  + Geiss an46",
  "NeW Adam Master Mashup FX 2 Geiss and Zylot - Reaction Diffusion 3 (Overload Mix 2) AMAZING MASUP Various + Hurricane Nightmare",
  "one-sided infinite-dimensional shape - helenisch",
  "orb - acid cycle [flexi shader mix] - yaqui graph",
  "ORB - Blue Emotion",
  "ORB - Fire and Fumes 2",
  "ORB - Lazer Ride",
  "ORB - Magma Pool",
  "ORB - Planetary Alignment Acid Burn",
  "ORB - Solar Radiation",
  "ORB - Waaa",
  "Phat + Zylot + Eo.S. - work with lines",
  "Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix",
  "Phat_Zylot_Eo.S. spiral_Movements_Beatle",
  "Phat_Zylot_Eo.S. square_faces_v2_alt_colours",
  "PieturP - triptrap_(getting_concrete_visions_through_a_diafragma_version)",
  "PieturP - triptrap_(ultimate-trip-mix)",
  "raron - a grayish blob - mash0000 - pungent gastric automata cloud fumes",
  "Redi Jedi - i dont think those were portabello mushrooms",
  "repressed americans - massive cheese lard nz+ redkneck treads",
  "Rocke - Answer.42 (New Mix 1) - mash0000 - slash and char p. jungle",
  "Rovastar & Idiot24-7 - Balk Acid",
  "Rovastar & Loadus + Zylot - FractalDrop (Spark Machine v2.0)",
  "Rovastar + Che - Asylum Animations",
  "Rovastar + Flexi - Hurricane Nightmare (Moebius Mix)",
  "Rovastar + Fvese - Mosaic Waves",
  "Rovastar + Geiss - Hurricane Nightmare",
  "Rovastar + Geiss - Hurricane Nightmare (Gold Chrome Mix)",
  "Rovastar + Geiss - Hurricane Nightmare (Relief Mix)",
  "Rovastar + Geiss - Snapshot Of Space (LSB mix)",
  "Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)",
  "Rovastar + Loadus + Geiss - Tone-mapped FractalDrop 7c",
  "Rovastar + Telek - Altars of Madness (Rolling Oceans Mix)",
  "Rovastar - A Million Miles From Earth (Wormhole Mix)",
  "Rovastar - Explosive Minds",
  "Rovastar - Harlequin′s Fractal Encounter - cancer of saints",
  "Rovastar - Hyperspace",
  "Rovastar - Oozing Resistance",
  "Rovastar - Torrid Tales",
  "Rovastar - Trippy Sperm (Jelly)",
  "Rovastar-altarsofmadness(forgottenrea",
  "Rozzor & Shreyas - Deeper Aesthetics",
  "sawtooth grin roam",
  "shifter + flexi - american oblivion pie",
  "shifter - dark tides bdrv mix",
  "shifter - dark tides bdrv mix 2",
  "shifter - escape (sigur ros)",
  "shifter - escape the worm - Eo.S. + Phat - Before_It_Eats_Your_Brain_Mix_v2",
  "shifter - feathers (angel wings)",
  "shifter - feathers (angel wings)_phat_remix relief 2",
  "shifter - fire and brimstone",
  "shifter - fractal grinder",
  "shifter - fuzzball 3d (glasses) false auralary2 undre thee bottom qoaguluste",
  "shifter - liquid circuitry - conjugoth",
  "shut down all survival paradigms",
  "Stahlregen & Boz + Eo.S + Geiss + Phat + Rovastar + Zylot - Machine Code [Jelly]",
  "Stahlregen & flexi + Geiss + Rovastar + Shifter - Fractal Feedback (for Hexcollie)",
  "stahlregen & geiss + rovastar - fields of flowers (mashup 9 - space flower rmx) - mash0001 - pack em in, we got a long haul + flashlight",
  "stahlregen + geiss + shifter - babylon",
  "stahlregen - dots (layered) - suksma world humanvirus replication killphreqs mix",
  "Stahlregen - Dots (Pixels - Blocky) (Jelly V2)",
  "stahlregen - old school, baby (spiral ornament)",
  "Studio Music and Unchained - Rapid Alteration",
  "suksma - barium titanate",
  "suksma - coal drapes - mrt fsh gordo dog crap in my bed cuz i sleep wid my shoes on",
  "suksma - diploautomatic autoimmunity vs passivematic aggpressive - troll",
  "suksma - ed geining hateops - flx i want you, i'm sick with you",
  "suksma - ed geining hateops - squeakers",
  "suksma - feign shoulder concern when i should be executed - everything is eternally shrinking",
  "suksma - grainery clock mortis",
  "suksma - heretical crosscut playpen",
  "suksma - Hexcollie - Julian Carnival - shimmy dumb grid",
  "suksma - nip tuck",
  "suksma - pus on my cat - j4+ - cubby",
  "suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression",
  "suksma - uninitialized variabowl (hydroponic chronic)",
  "suksma - youtube PQsWLhvuKk8 - waving goodbye to earth",
  "Telek - Sine Wave",
  "The NG + Flexi + BDRV - Ultramix, Aderrasi + Flexi - Predator Prey Spirals, Flexi - Jellyfish Jam",
  "TonyMilkdrop - Magellan's Nebula [Flexi - fancy + $this shall not retain]",
  "TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse]",
  "Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)",
  "Unchained - All You Can Eat",
  "Unchained - Fuzzy Sciences",
  "Unchained - Making a Science of It 4",
  "Unchained - Unified Drag 2",
  "undulate harque - shit broo",
  "va ultramix - 154 [chaos]",
  "various artists - 1200774354134 - mash0000 - what the writer′s guild is doing with the extra money",
  "Waltra - Cosmic Wind",
  "Waltra - Heaven Liquid",
  "Waltra - Ice Plasma",
  "Waltra - Square Orgy",
  "yin - 190 - Temporal fluctuations",
  "yin - 191 - Temporal singularities",
  "yin - 250 - Artificial poles of the continuum_Phat′s_Orbit_mix",
  "yin - 253 - Artificial poles of the continuum (remix #3)",
  "yin - 315 - Ocean of Light (yo im peakin yo Eo.S.-Phat)",
  "yin - 352 - Chromatron (warped)",
  "yin - 393 - Artificial Inspiration (music driven - outward)",
  "Zylot - In death there is life (Geiss Layered Mix)",
  "Zylot - In death there is life (Geiss Layered Mix) (Jelly)",
  "Zylot - Paint Spill (Music Reactive Paint Mix)",
  "Zylot - Star Ornament",
  "Zylot - True Visionary",
  "Zylot - True Visionary (Final Mix)",
];
