// Copyright 2023 Im-Beast. MIT license.

// PKG-004: examples are a MACHINE-READABLE REGISTRY, and docs may embed
// only entries the registry proves compile against the current public
// entrypoints. Each entry declares its name, path, capability tags
// (derived from a structured header comment, defaulting to "demo"), the
// permissions its launcher grants, and the exact playground command. The
// registry file is generated by script and gated in CI: a single
// deno-check pass over every registered path fails the gate when any
// example stops compiling, so a stale example can never be embedded.

/** One registry entry. */
export interface ExampleEntry {
  readonly name: string;
  readonly path: string;
  readonly capabilities: readonly string[];
  /** Permission flags the playground launcher passes. */
  readonly permissions: readonly string[];
  /** The exact local playground command. */
  readonly command: string;
}

/** The registry document. */
export interface ExampleRegistry {
  readonly version: 1;
  readonly entries: readonly ExampleEntry[];
}

/** Parses one example source's declarations into an entry. */
export function entryForExample(path: string, source: string): ExampleEntry {
  const name = path.split("/").pop()!.replace(/\.ts$/, "");
  const capabilityMatch = source.match(/@example-capabilities\s+([^\n*]+)/);
  const permissionMatch = source.match(/@example-permissions\s+([^\n*]+)/);
  const capabilities = capabilityMatch ? capabilityMatch[1]!.trim().split(/\s*,\s*/) : ["demo"];
  const permissions = permissionMatch ? permissionMatch[1]!.trim().split(/\s*,\s*/) : ["-A"];
  return {
    name,
    path,
    capabilities,
    permissions,
    command: `deno run ${permissions.join(" ")} ${path}`,
  };
}

/** Builds the registry from example paths and sources. */
export function buildExampleRegistry(
  examples: readonly { readonly path: string; readonly source: string }[],
): ExampleRegistry {
  return {
    version: 1,
    entries: examples
      .map((example) => entryForExample(example.path, example.source))
      .sort((a, b) => a.name.localeCompare(b.name)),
  };
}
