import * as esbuild from "esbuild";
import { resolve } from "node:path";

const outdir = "docs/assets";
const webExternalSpecifiers = new Map([
  // The optional PTY adapter is reached through an import-map alias and is only
  // ever dynamically imported on the server. Keep the specifier intact and
  // external so the browser bundle never tries to resolve a native FFI package.
  ["@sigma/pty-ffi", "jsr:@sigma/pty-ffi@0.42.0"],
  ["crayon", "https://deno.land/x/crayon@3.3.3/mod.ts"],
  ["jpeg-js", "https://esm.sh/jpeg-js@0.4.4"],
  ["pngjs", "https://esm.sh/pngjs@7.0.0"],
  ["three", "https://esm.sh/three@0.183.2"],
  ["three/tsl", "https://esm.sh/three@0.183.2/tsl"],
  ["three/webgpu", "https://esm.sh/three@0.183.2/webgpu"],
]);
const webExternalSpecifierPattern = /^(?:@sigma\/pty-ffi|crayon|jpeg-js|pngjs|three(?:\/(?:tsl|webgpu))?)$/;
const treeShakeSafeLibraryModules = new Set([
  resolve("src/unicode/width.ts"),
  // The web-parity exports: pure computation with no import-time side effects,
  // marked so a page that ignores them does not carry them. A module whose
  // import must run for its side effect can never appear here.
  resolve("src/canvas/dirty_region.ts"),
  resolve("src/canvas/pixel_samplers.ts"),
  resolve("src/canvas/spatial_index.ts"),
  resolve("src/key_sequences.ts"),
  resolve("src/keymap.ts"),
  resolve("src/keymap_layers.ts"),
  resolve("src/permissions.ts"),
  resolve("src/surface_animation.ts"),
  resolve("src/theme_contrast.ts"),
  resolve("src/theme_density.ts"),
  resolve("src/theme_expressions.ts"),
  resolve("src/theme_icons.ts"),
  resolve("src/theme_interchange.ts"),
  resolve("src/theme_motion.ts"),
  resolve("src/theme_oklch.ts"),
  resolve("src/theme_quantize.ts"),
  resolve("src/theme_token_schemas.ts"),
]);
const treeShakeSafeLibraryPrefixes = [
  `${resolve("src/i18n")}/`,
  `${resolve("src/perf")}/`,
];

// Web parity ratchet. `mod.web.ts` still carries guarded terminal paths in its
// graph — every name here is dead code behind a runtime check in a browser,
// proven by the shipped workbench page. The list may shrink; a NEW Deno API
// appearing in the web root means something terminal-bound was exported to the
// web surface, and this build refuses it before a page can break.
const WEB_ROOT_ALLOWED_DENO_REFS = new Set([
  "Deno.addSignalListener",
  "Deno.build",
  "Deno.Command",
  "Deno.consoleSize",
  "Deno.env",
  "Deno.errors",
  "Deno.exit",
  "Deno.permissions",
  "Deno.pid",
  "Deno.readFile",
  "Deno.readTextFile",
  "Deno.readTextFileSync",
  "Deno.removeSignalListener",
  "Deno.stdin",
  "Deno.stdout",
  "Deno.watchFs",
  "Deno.writeTextFile",
]);

if (import.meta.main) {
  await Deno.mkdir(outdir, { recursive: true });
  await removeLegacyDemoAssets();
  await buildPageBundle("examples/web/api_workbench_page.ts", `${outdir}/api-workbench.js`);
  await buildPageBundle("examples/web/desktop_page.ts", `${outdir}/desktop.js`);
  await verifyWebSurface("mod.web.ts", WEB_ROOT_ALLOWED_DENO_REFS);
  // The desktop ships as the landing page; it may lean on the same guarded
  // paths as the web root, and not one more.
  await verifyWebSurface("examples/web/desktop_page.ts", WEB_ROOT_ALLOWED_DENO_REFS);
  // The visualisation entrypoints hold a stricter line: zero Deno references,
  // so a browser can import them without a single guarded terminal path.
  await verifyWebSurface("src/viz/mod.ts", new Set());
  await verifyWebSurface("src/viz/three/mod.ts", new Set());
  // The browser monitor reuses the terminal monitor's compose/feeds/tiles;
  // this proves that reuse stays value-level clean (its Snapshot import is
  // type-only and must remain so).
  await verifyWebSurface("examples/web/exomonitor_page.ts", new Set());
  esbuild.stop();

  await Deno.writeTextFile("docs/index.html", desktopHtml());
  await Deno.writeTextFile("docs/workbench.html", workbenchHtml());
  await formatGeneratedHtml();
}

async function buildPageBundle(entryPoint: string, outfile: string): Promise<void> {
  await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    target: ["es2022"],
    treeShaking: true,
    minify: true,
    outfile,
    banner: {
      js: "// Generated by `deno task web:pages:build`. Do not edit directly.",
    },
    plugins: [treeShakeSafeLibraryModulesPlugin(), webExternalDependencyPlugin()],
  });
}

function treeShakeSafeLibraryModulesPlugin(): esbuild.Plugin {
  return {
    name: "tree-shake-safe-library-modules",
    setup(build) {
      build.onResolve({ filter: /\.ts$/ }, (args) => {
        if (args.resolveDir.length === 0) return undefined;
        const path = resolve(args.resolveDir, args.path);
        const safe = treeShakeSafeLibraryModules.has(path) ||
          treeShakeSafeLibraryPrefixes.some((prefix) => path.startsWith(prefix));
        if (!safe) return undefined;
        return { path, sideEffects: false };
      });
    },
  };
}

/**
 * Bundles an entrypoint for the browser without writing it, and fails when the
 * output references a Deno API the allowlist does not carry. esbuild sees the
 * value-level graph exactly as a page would, which is what makes this a parity
 * gate rather than a type check: a type-only import costs nothing here, a real
 * one is caught before it ships.
 */
async function verifyWebSurface(entryPoint: string, allowed: ReadonlySet<string>): Promise<void> {
  const result = await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    target: ["es2022"],
    treeShaking: true,
    write: false,
    logLevel: "silent",
    plugins: [treeShakeSafeLibraryModulesPlugin(), webExternalDependencyPlugin()],
  });
  const output = result.outputFiles?.[0]?.text ?? "";
  const refs = new Set([...output.matchAll(/Deno\.[a-zA-Z]+/g)].map((match) => match[0]));
  const violations = [...refs].filter((ref) => !allowed.has(ref)).sort();
  if (violations.length > 0) {
    throw new Error(
      `${entryPoint} bundles Deno APIs the web surface does not allow: ${violations.join(", ")}. ` +
        "Something terminal-bound reached the web export graph.",
    );
  }
}

async function removeLegacyDemoAssets(): Promise<void> {
  await Promise.all([
    removeIfExists(`${outdir}/api-workbench.js.map`),
    removeIfExists(`${outdir}/neon-exodus.js`),
    removeIfExists(`${outdir}/neon-exodus.js.map`),
    removeIfExists(`${outdir}/three-ascii-web.js`),
    removeIfExists(`${outdir}/three-ascii-web.js.map`),
    removeIfExists(`${outdir}/assets`),
  ]);
}

async function removeIfExists(path: string): Promise<void> {
  try {
    await Deno.remove(path, { recursive: true });
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
}

async function formatGeneratedHtml(): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "docs/index.html", "docs/workbench.html"],
    stdout: "null",
    stderr: "inherit",
  });
  const status = await command.output();
  if (!status.success) {
    throw new Error("Failed to format generated docs/index.html.");
  }
}

function webExternalDependencyPlugin(): esbuild.Plugin {
  return {
    name: "web-external-dependency",
    setup(build) {
      build.onResolve({ filter: webExternalSpecifierPattern }, (args) => ({
        path: webExternalSpecifiers.get(args.path)!,
        external: true,
      }));
      build.onResolve({ filter: /^npm:/ }, (args) => ({
        path: npmSpecifierToEsmSh(args.path),
        external: true,
      }));
      build.onResolve({ filter: /^jsr:/ }, (args) => ({
        path: args.path,
        external: true,
      }));
    },
  };
}

function npmSpecifierToEsmSh(specifier: string): string {
  return specifier.replace(/^npm:/, "https://esm.sh/");
}

function desktopHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>exotui desktop</title>
    <style>
      :root {
        color-scheme: dark;
        background: #0a0c14;
        color: #e2e8f4;
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      }

      html,
      body {
        width: 100%;
        height: 100%;
        margin: 0;
        overflow: hidden;
        overscroll-behavior: none;
      }

      #app {
        width: 100vw;
        height: 100vh;
        outline: none;
        touch-action: none;
        user-select: none;
        background: #0a0c14;
      }

      canvas {
        display: block;
        width: 100%;
        height: 100%;
        touch-action: none;
        user-select: none;
      }
    </style>
  </head>
  <body>
    <div id="app" aria-label="exotui desktop demo"></div>
    <script type="module" src="./assets/desktop.js"></script>
  </body>
</html>
`;
}

function workbenchHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Deno TUI Portfolio Demo</title>
    <style>
      :root {
        color-scheme: dark;
        background: #05070d;
        color: #eff7ff;
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      }

      html,
      body {
        width: 100%;
        height: 100%;
        margin: 0;
        overscroll-behavior: none;
      }

      body {
        min-height: 100vh;
        overflow: hidden;
        display: grid;
        grid-template-rows: auto minmax(0, 1fr);
        background:
          radial-gradient(circle at 20% 0%, rgba(255, 66, 49, 0.18), transparent 32rem),
          radial-gradient(circle at 90% 10%, rgba(177, 124, 255, 0.16), transparent 34rem),
          #05070d;
      }

      header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
        padding: 0.75rem 1rem;
        border-bottom: 1px solid rgba(239, 247, 255, 0.16);
        background: rgba(5, 7, 13, 0.82);
      }

      h1 {
        margin: 0;
        color: #ff4231;
        font-size: clamp(1rem, 2vw, 1.35rem);
        letter-spacing: 0;
      }

      p {
        margin: 0;
        color: #5a6478;
        font-size: 0.9rem;
      }

      .portfolio-shell {
        display: grid;
        width: 100vw;
        height: 100%;
        min-height: 0;
      }

      .terminal-host {
        width: 100%;
        height: 100%;
        outline: none;
        touch-action: none;
        user-select: none;
        box-shadow: inset 0 0 0 1px rgba(177, 124, 255, 0.24), 0 0 48px rgba(177, 124, 255, 0.12);
        background: #05070d;
      }

      @media (max-width: 720px) {
        header {
          align-items: flex-start;
          flex-direction: column;
          gap: 0.25rem;
        }
      }

      canvas {
        display: block;
        width: 100%;
        height: 100%;
        touch-action: none;
        user-select: none;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>Deno TUI Portfolio Demo</h1>
      <p>Standalone browser build of the API Workbench portfolio: windows, menus, controls, tables, themes, and canvas rendering.</p>
    </header>
    <div class="portfolio-shell">
      <main id="api-workbench" class="terminal-host" aria-label="API Workbench portfolio browser demo"></main>
    </div>
    <script type="module" src="./assets/api-workbench.js"></script>
  </body>
</html>
`;
}
