import { stripAnsi } from "../src/utils/ansi_text.ts";

export interface E2ECommandTarget {
  id: string;
  label: string;
  command: readonly string[];
  required?: readonly string[];
  forbidden?: readonly string[];
  timeoutMs?: number;
}

export interface E2EArtifactTarget {
  id: string;
  label: string;
  path: string;
  required?: readonly string[];
  forbidden?: readonly string[];
  minBytes?: number;
  maxBytes?: number;
}

export interface E2ECommandResult extends E2ECommandTarget {
  code: number;
  passed: boolean;
  durationMs: number;
  missing: string[];
  forbiddenMatches: string[];
  outputPreview: string;
}

export interface E2EArtifactResult extends E2EArtifactTarget {
  passed: boolean;
  bytes: number;
  missing: string[];
  forbiddenMatches: string[];
  error?: string;
}

export interface E2EReport {
  passed: boolean;
  durationMs: number;
  commands: E2ECommandResult[];
  artifacts: E2EArtifactResult[];
}

export const e2eCommandTargets: readonly E2ECommandTarget[] = [
  {
    id: "pages-build",
    label: "GitHub Pages Build",
    command: ["deno", "task", "web:pages:build"],
    timeoutMs: 20_000,
  },
  {
    id: "web-demo-check",
    label: "Web Demo Type Check",
    command: ["deno", "task", "web:demo:check"],
    required: ["examples/web/neon_exodus_page.ts", "examples/web/api_workbench_page.ts"],
  },
  {
    id: "web-runtime-tests",
    label: "Web Runtime Tests",
    command: ["deno", "task", "web:test"],
    required: ["web_runtime.test.ts", "web_remote_terminal.test.ts", "canvas_sink.test.ts", "passed"],
  },
  {
    id: "demo-gallery",
    label: "Console Demo Gallery",
    command: ["deno", "task", "demo-gallery"],
    required: ["# Demo Gallery", "Recommended Tour", "Terminal plan:"],
  },
  {
    id: "component-catalog",
    label: "Component Catalog Report",
    command: ["deno", "task", "component-catalog"],
    required: ["# Component Catalog", "TextBox", "WindowManager", "ThreeAscii"],
  },
  {
    id: "app-plugin-catalog",
    label: "App Plugin Catalog Report",
    command: ["deno", "task", "app-plugin-catalog"],
    required: ["# App Plugin Registry", "Data Query Pack", "Runtime Pack"],
  },
  {
    id: "capabilities",
    label: "Runtime And Terminal Capabilities",
    command: ["deno", "task", "capabilities"],
    required: ["Runtime capabilities", "Terminal capabilities", "Terminal plan:"],
  },
  {
    id: "benchmark-catalog",
    label: "Benchmark Catalog",
    command: ["deno", "task", "benchmark", "--", "--list"],
    required: ["# Benchmark Catalog", "input/mouse-hit-test-500-targets", "runtime/scheduler-batch-100"],
  },
  {
    id: "api-inventory-gate",
    label: "API Inventory Gate",
    command: [
      "deno",
      "task",
      "api-inventory",
      "--",
      "--check",
      "--quiet",
      "--fail-duplicates",
      "--min-doc-coverage=1",
    ],
  },
  {
    id: "package-check",
    label: "Package Export Map Gate",
    command: ["deno", "task", "package-check", "--", "--quiet"],
  },
];

export const e2eArtifactTargets: readonly E2EArtifactTarget[] = [
  {
    id: "pages-html",
    label: "GitHub Pages HTML",
    path: "docs/index.html",
    minBytes: 500,
    required: [
      "exotui desktop",
      "./assets/desktop.js",
    ],
  },
  {
    id: "workbench-html",
    label: "API Workbench HTML",
    path: "docs/workbench.html",
    minBytes: 1_000,
    required: [
      "Deno TUI Portfolio Demo",
      "API Workbench portfolio browser demo",
      "./assets/api-workbench.js",
    ],
  },
  {
    id: "web-desktop-bundle",
    label: "Desktop Web Bundle",
    path: "docs/assets/desktop.js",
    minBytes: 10_000,
    // Set against a 680_017-byte first build: the window host, the viz layer,
    // the neon suite and the browser monitor in one bundle. Headroom is for
    // demos joining the launcher; a jump past it means something imported the
    // terminal side of the library and must be caught, not absorbed.
    maxBytes: 780_000,
    required: ["Generated by `deno task web:pages:build`"],
  },
  {
    id: "web-desktop-three-bundle",
    label: "Desktop Three Lazy Bundle",
    path: "docs/assets/desktop-three.js",
    minBytes: 10_000,
    // The lazily loaded WebGPU ASCII pipeline; `three` itself is external and
    // arrives from esm.sh, so growth here means library code, not vendored
    // geometry.
    maxBytes: 220_000,
    required: ["Generated by `deno task web:pages:build`"],
  },
  {
    id: "web-workbench-bundle",
    label: "API Workbench Web Bundle",
    path: "docs/assets/api-workbench.js",
    minBytes: 10_000,
    // 500_000 was set at 93f90868 against a 373_457-byte bundle. The demo has
    // grown ~51% since; the artifact is minified and tree-shaken already, and
    // its 566 KB is spread over 155 modules with no chunk above 6.5%, so there
    // is no build-level fix left — shrinking it means changing what the demo
    // does. The gate read 532_789 for a while, but that was a STALE artifact:
    // web:pages:build had been failing since the 040 follow-up, and a failing
    // build produces nothing to measure. Raised to a truthful number so the
    // ratchet still catches growth. Getting back under 500_000 is owed work,
    // tracked in plan/todo/priority.md.
    maxBytes: 600_000,
    required: ["Generated by `deno task web:pages:build`"],
  },
];

export async function runE2ESuite(
  options: {
    commands?: readonly E2ECommandTarget[];
    artifacts?: readonly E2EArtifactTarget[];
    cwd?: string;
  } = {},
): Promise<E2EReport> {
  const started = performance.now();
  const commands: E2ECommandResult[] = [];
  for (const target of options.commands ?? e2eCommandTargets) {
    commands.push(await runE2ECommandTarget(target, { cwd: options.cwd }));
  }
  const artifacts: E2EArtifactResult[] = [];
  for (const target of options.artifacts ?? e2eArtifactTargets) {
    artifacts.push(await inspectE2EArtifactTarget(target, { cwd: options.cwd }));
  }
  return {
    passed: commands.every((result) => result.passed) && artifacts.every((result) => result.passed),
    durationMs: Math.round(performance.now() - started),
    commands,
    artifacts,
  };
}

export async function runE2ECommandTarget(
  target: E2ECommandTarget,
  options: { cwd?: string } = {},
): Promise<E2ECommandResult> {
  const started = performance.now();
  const command = new Deno.Command(target.command[0]!, {
    args: [...target.command.slice(1)],
    cwd: options.cwd,
    stdout: "piped",
    stderr: "piped",
    signal: AbortSignal.timeout(target.timeoutMs ?? 30_000),
  });
  try {
    const output = await command.output();
    return inspectE2ECommandOutput(target, {
      code: output.code,
      stdout: new TextDecoder().decode(output.stdout),
      stderr: new TextDecoder().decode(output.stderr),
      durationMs: Math.round(performance.now() - started),
    });
  } catch (error) {
    return inspectE2ECommandOutput(target, {
      code: 1,
      stdout: "",
      stderr: error instanceof Error ? error.message : String(error),
      durationMs: Math.round(performance.now() - started),
    });
  }
}

export function inspectE2ECommandOutput(
  target: E2ECommandTarget,
  output: { code: number; stdout: string; stderr?: string; durationMs?: number },
): E2ECommandResult {
  const text = stripAnsi(`${output.stdout}\n${output.stderr ?? ""}`);
  const missing = (target.required ?? []).filter((token) => !text.includes(token));
  const forbiddenMatches = (target.forbidden ?? defaultForbiddenTokens).filter((token) => text.includes(token));
  return {
    ...target,
    code: output.code,
    passed: output.code === 0 && missing.length === 0 && forbiddenMatches.length === 0,
    durationMs: output.durationMs ?? 0,
    missing,
    forbiddenMatches,
    outputPreview: previewText(text),
  };
}

export async function inspectE2EArtifactTarget(
  target: E2EArtifactTarget,
  options: { cwd?: string } = {},
): Promise<E2EArtifactResult> {
  const path = options.cwd ? `${options.cwd.replace(/\/$/, "")}/${target.path}` : target.path;
  try {
    const data = await Deno.readFile(path);
    const text = isLikelyText(target.path) ? new TextDecoder().decode(data) : "";
    return inspectE2EArtifactData(target, data.byteLength, text);
  } catch (error) {
    return {
      ...target,
      passed: false,
      bytes: 0,
      missing: [...(target.required ?? [])],
      forbiddenMatches: [],
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

export function inspectE2EArtifactData(target: E2EArtifactTarget, bytes: number, text = ""): E2EArtifactResult {
  const missing = (target.required ?? []).filter((token) => !text.includes(token));
  const forbiddenMatches = (target.forbidden ?? []).filter((token) => text.includes(token));
  const tooSmall = bytes < (target.minBytes ?? 1);
  const tooLarge = target.maxBytes !== undefined && bytes > target.maxBytes;
  return {
    ...target,
    passed: !tooSmall && !tooLarge && missing.length === 0 && forbiddenMatches.length === 0,
    bytes,
    missing: [
      ...(tooSmall ? [`minBytes:${target.minBytes ?? 1}`] : []),
      ...(tooLarge ? [`maxBytes:${target.maxBytes}`] : []),
      ...missing,
    ],
    forbiddenMatches,
  };
}

export function formatE2EReport(report: E2EReport): string {
  const commandRows = report.commands.map((result) =>
    `| ${result.passed ? "pass" : "fail"} | ${result.id} | ${result.durationMs} | ${result.code} | ${
      result.missing.join(", ") || "-"
    } | ${result.forbiddenMatches.join(", ") || "-"} |`
  );
  const artifactRows = report.artifacts.map((result) =>
    `| ${result.passed ? "pass" : "fail"} | ${result.id} | ${result.bytes} | ${result.missing.join(", ") || "-"} | ${
      result.forbiddenMatches.join(", ") || "-"
    } |`
  );
  const failed = [
    ...report.commands.filter((result) => !result.passed).map((result) => ({
      label: result.label,
      preview: result.outputPreview,
    })),
    ...report.artifacts.filter((result) => !result.passed).map((result) => ({
      label: result.label,
      preview: result.error ??
        `missing: ${result.missing.join(", ") || "-"}; forbidden: ${result.forbiddenMatches.join(", ") || "-"}`,
    })),
  ];
  return [
    "# End-To-End Report",
    "",
    `Status: ${report.passed ? "pass" : "fail"}`,
    `Duration: ${report.durationMs}ms`,
    "",
    "## Commands",
    "",
    "| Status | Target | ms | Code | Missing | Forbidden |",
    "| --- | --- | ---: | ---: | --- | --- |",
    ...commandRows,
    "",
    "## Artifacts",
    "",
    "| Status | Artifact | Bytes | Missing | Forbidden |",
    "| --- | --- | ---: | --- | --- |",
    ...artifactRows,
    ...(failed.length
      ? [
        "",
        "## Failed Output Previews",
        "",
        ...failed.flatMap((failure) => [
          `### ${failure.label}`,
          "",
          "```text",
          failure.preview,
          "```",
          "",
        ]),
      ]
      : []),
  ].join("\n");
}

const defaultForbiddenTokens = [
  "ReferenceError",
  "TypeError",
  "RangeError",
  "SyntaxError",
  "error: Uncaught",
  "FAILED |",
] as const;

function isLikelyText(path: string): boolean {
  return /\.(html|js|css|json|map|txt|md)$/i.test(path);
}

function previewText(value: string): string {
  return value.split("\n").slice(0, 20).join("\n").trimEnd();
}

if (import.meta.main) {
  const json = Deno.args.includes("--json");
  const quiet = Deno.args.includes("--quiet");
  const report = await runE2ESuite();
  if (json) {
    console.log(JSON.stringify(report, null, 2));
  } else if (!quiet) {
    console.log(formatE2EReport(report));
  }
  if (!report.passed) Deno.exit(1);
}
