// Copyright 2023 Im-Beast. MIT license.

// Generates the pinned UAX #14 line-break data module and test fixture.
// Follows the TXT-001 data-pack discipline: every network input is pinned by
// SHA-256, the emitted module digest is reviewed in the same patch, and
// `--check` verifies the checked-in module and fixture without any network.
//
//   deno run -A scripts/update_unicode_linebreak.ts          # regenerate
//   deno run -A --deny-net scripts/update_unicode_linebreak.ts --check

const UNICODE_VERSION = "17.0.0";
const OUTPUT_PATH = new URL("../src/unicode/generated/unicode_17_0_0_linebreak.ts", import.meta.url);
const TEST_FIXTURE_PATH = new URL("../tests/fixtures/unicode/LineBreakTest-17.0.0.txt", import.meta.url);
const MAX_SOURCE_BYTES = 4_000_000;

const SOURCES = Object.freeze({
  lineBreak: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/LineBreak.txt`,
    sha256: "e6a18fa91f8f6a6f8e534b1d3f128c21ada45bfe152eb6b1bcc5e15fd8ac92e6",
  },
  generalCategory: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/extracted/DerivedGeneralCategory.txt`,
    sha256: "d62e5bab70ca74f099343f71224fa051cb1fdd61a1ab45c0488c44cfc0b6102e",
  },
  eastAsianWidth: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/EastAsianWidth.txt`,
    sha256: "ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33",
  },
  emoji: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/emoji/emoji-data.txt`,
    sha256: "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
  },
  test: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/auxiliary/LineBreakTest.txt`,
    sha256: "e69884e0dde6a8724873f885d68c52dc14518abf9ae4ca9e2283b8773db3b752",
  },
});

// A regeneration is deliberately incomplete until this reviewed digest is
// updated in the same patch.
const REVIEWED_MODULE_SHA256 = "963a24ceeb4dfcfab87a8b307339282de640d8bb36bd5da0fb49108f6fab503d";

const MODULE_PREFIX = `// Copyright 2023 Im-Beast. MIT license.
// Generated by scripts/update_unicode_linebreak.ts from pinned unicode.org inputs.
// Do not edit by hand; run the network-free --check mode in CI.

/** Checked-in Unicode ${UNICODE_VERSION} UAX #14 line-break data. */
export const GENERATED_UNICODE_17_0_0_LINE_BREAK_DATA: unknown = JSON.parse(String.raw\``;
const MODULE_SUFFIX = "`);\n";

async function sha256(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function download(source: { url: string; sha256: string }): Promise<string> {
  const response = await fetch(source.url);
  if (!response.ok) throw new Error(`${source.url}: HTTP ${response.status}`);
  const text = await response.text();
  if (text.length > MAX_SOURCE_BYTES) throw new Error(`${source.url}: exceeds ${MAX_SOURCE_BYTES} bytes`);
  const digest = await sha256(text);
  if (digest !== source.sha256) {
    throw new Error(`${source.url}: unpinned content ${digest} (expected ${source.sha256})`);
  }
  return text;
}

interface PropertyRange {
  start: number;
  end: number;
  value: string;
}

function parsePropertyFile(text: string): PropertyRange[] {
  const ranges: PropertyRange[] = [];
  for (const line of text.split("\n")) {
    const body = line.split("#")[0]!.trim();
    if (!body) continue;
    const [codes, value] = body.split(";").map((part) => part.trim());
    if (!codes || !value) continue;
    const [startHex, endHex] = codes.split("..");
    const start = Number.parseInt(startHex!, 16);
    const end = Number.parseInt(endHex ?? startHex!, 16);
    ranges.push({ start, end, value });
  }
  ranges.sort((left, right) => left.start - right.start);
  return ranges;
}

function toSet(ranges: PropertyRange[], accept: (value: string) => boolean): PropertyRange[] {
  const kept = ranges.filter((range) => accept(range.value)).map((range) => ({ ...range, value: "" }));
  // Merge adjacent ranges for compactness.
  const merged: PropertyRange[] = [];
  for (const range of kept) {
    const last = merged.at(-1);
    if (last && range.start <= last.end + 1) last.end = Math.max(last.end, range.end);
    else merged.push(range);
  }
  return merged;
}

function inSet(ranges: PropertyRange[], codePoint: number): boolean {
  let low = 0;
  let high = ranges.length - 1;
  while (low <= high) {
    const mid = (low + high) >> 1;
    const range = ranges[mid]!;
    if (codePoint < range.start) high = mid - 1;
    else if (codePoint > range.end) low = mid + 1;
    else return true;
  }
  return false;
}

/** start-delta/length/value-index triplets, exactly like the pack encoding. */
function encodeTriplets(ranges: PropertyRange[], values: readonly string[]): number[] {
  const out: number[] = [];
  let previousEnd = 0;
  for (const range of ranges) {
    out.push(range.start - previousEnd, range.end - range.start, values.indexOf(range.value));
    previousEnd = range.end + 1;
  }
  return out;
}

function encodePairs(ranges: PropertyRange[]): number[] {
  const out: number[] = [];
  let previousEnd = 0;
  for (const range of ranges) {
    out.push(range.start - previousEnd, range.end - range.start);
    previousEnd = range.end + 1;
  }
  return out;
}

async function build(): Promise<{ moduleText: string; testText: string }> {
  const [lineBreakText, gcText, eawText, emojiText, testText] = await Promise.all([
    download(SOURCES.lineBreak),
    download(SOURCES.generalCategory),
    download(SOURCES.eastAsianWidth),
    download(SOURCES.emoji),
    download(SOURCES.test),
  ]);
  if (!testText.startsWith(`# LineBreakTest-${UNICODE_VERSION}.txt`)) {
    throw new Error("LineBreakTest fixture version header is not pinned.");
  }

  const gcRanges = parsePropertyFile(gcText);
  const mnMc = toSet(gcRanges, (value) => value === "Mn" || value === "Mc");
  const pi = toSet(gcRanges, (value) => value === "Pi");
  const pf = toSet(gcRanges, (value) => value === "Pf");
  const cn = toSet(gcRanges, (value) => value === "Cn");
  const eastAsian = toSet(parsePropertyFile(eawText), (value) => value === "F" || value === "W" || value === "H");
  const extendedPictographic = toSet(
    parsePropertyFile(emojiText),
    (value) => value === "Extended_Pictographic",
  );

  // LB1 folds at generation time: AI/SG/XX → AL, SA → CM (Mn/Mc) or AL.
  // QU splits by Pi/Pf so LB15a/b and LB19a resolve from the class alone.
  // CJ is kept: the runtime resolves it per tailoring (NS by default).
  const folded: PropertyRange[] = [];
  for (const range of parsePropertyFile(lineBreakText)) {
    for (let start = range.start; start <= range.end;) {
      let value = range.value;
      let end = range.end;
      if (value === "AI" || value === "SG" || value === "XX") value = "AL";
      else if (value === "SA") {
        const combining = inSet(mnMc, start);
        value = combining ? "CM" : "AL";
        end = start;
        for (let probe = start + 1; probe <= range.end && inSet(mnMc, probe) === combining; probe += 1) end = probe;
      } else if (value === "QU") {
        const kind = inSet(pi, start) ? "QU_Pi" : inSet(pf, start) ? "QU_Pf" : "QU";
        value = kind;
        end = start;
        for (
          let probe = start + 1;
          probe <= range.end && (inSet(pi, probe) ? "QU_Pi" : inSet(pf, probe) ? "QU_Pf" : "QU") === kind;
          probe += 1
        ) end = probe;
      }
      if (value !== "AL") folded.push({ start, end, value }); // AL is the runtime default
      start = end + 1;
    }
  }
  folded.sort((left, right) => left.start - right.start);
  const compact: PropertyRange[] = [];
  for (const range of folded) {
    const last = compact.at(-1);
    if (last && last.value === range.value && range.start === last.end + 1) last.end = range.end;
    else compact.push({ ...range });
  }

  const values = [...new Set(compact.map((range) => range.value))].sort();
  const extPictCn: PropertyRange[] = [];
  for (const range of extendedPictographic) {
    for (let cp = range.start; cp <= range.end; cp += 1) {
      if (!inSet(cn, cp)) continue;
      const last = extPictCn.at(-1);
      if (last && cp === last.end + 1) last.end = cp;
      else extPictCn.push({ start: cp, end: cp, value: "" });
    }
  }

  const payload = {
    schema: "deno-tui.unicode-line-break-data",
    schemaVersion: 1,
    unicodeVersion: UNICODE_VERSION,
    values,
    ranges: encodeTriplets(compact, values),
    eastAsian: encodePairs(eastAsian),
    extPictCn: encodePairs(extPictCn),
    sources: Object.fromEntries(Object.entries(SOURCES).map(([name, source]) => [name, source.sha256])),
  };
  const moduleText = `${MODULE_PREFIX}${JSON.stringify(payload)}${MODULE_SUFFIX}`;
  return { moduleText, testText };
}

async function check(): Promise<void> {
  const moduleText = await Deno.readTextFile(OUTPUT_PATH);
  const digest = await sha256(moduleText);
  if (digest !== REVIEWED_MODULE_SHA256) {
    throw new Error(`line-break module is unreviewed: ${digest} (expected ${REVIEWED_MODULE_SHA256})`);
  }
  const fixture = await Deno.readTextFile(TEST_FIXTURE_PATH);
  const fixtureDigest = await sha256(fixture);
  if (fixtureDigest !== SOURCES.test.sha256) {
    throw new Error(`LineBreakTest fixture drifted: ${fixtureDigest} (expected ${SOURCES.test.sha256})`);
  }
  console.log(`line-break data verified: module ${digest}`);
}

if (Deno.args.includes("--check")) {
  await check();
} else {
  const { moduleText, testText } = await build();
  await Deno.writeTextFile(OUTPUT_PATH, moduleText);
  await Deno.writeTextFile(TEST_FIXTURE_PATH, testText);
  console.log(`wrote ${OUTPUT_PATH.pathname}`);
  console.log(`module sha256: ${await sha256(moduleText)} (update REVIEWED_MODULE_SHA256)`);
}
