// Copyright 2023 Im-Beast. MIT license.

// Generates the pinned UAX #9 bidi data module and test fixture, under the
// TXT-001 discipline: SHA-256-pinned inputs, a reviewed module digest, and a
// network-free --check mode.
//
//   deno run -A scripts/update_unicode_bidi.ts          # regenerate
//   deno run -A --deny-net scripts/update_unicode_bidi.ts --check

const UNICODE_VERSION = "17.0.0";
const OUTPUT_PATH = new URL("../src/unicode/generated/unicode_17_0_0_bidi.ts", import.meta.url);
const TEST_FIXTURE_PATH = new URL("../tests/fixtures/unicode/BidiCharacterTest-17.0.0.txt", import.meta.url);
const MAX_SOURCE_BYTES = 8_000_000;

const SOURCES = Object.freeze({
  bidiClass: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/extracted/DerivedBidiClass.txt`,
    sha256: "4867b4b7f0731ed1bfcd34cc6251211ff1542541fce0734b6fbda139ee80b3a4",
  },
  brackets: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/BidiBrackets.txt`,
    sha256: "dadbaf38a0d0246e5b805bf8725cb81b7c621f93d030595635f5ba2c2f179428",
  },
  test: {
    url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/BidiCharacterTest.txt`,
    sha256: "a3e6e905ab5afbe318a96df5401d0372a04cd73ef139ab5e3cf0ae241c255488",
  },
});

// A regeneration is deliberately incomplete until this digest is updated in
// the same patch.
const REVIEWED_MODULE_SHA256 = "f27ac060ccc417674d80218537282451f03e31f120c74f111b68d6f4b6d11ccd";

const LONG_TO_SHORT: Readonly<Record<string, string>> = {
  Left_To_Right: "L",
  Right_To_Left: "R",
  Arabic_Letter: "AL",
  European_Number: "EN",
  European_Separator: "ES",
  European_Terminator: "ET",
  Arabic_Number: "AN",
  Common_Separator: "CS",
  Nonspacing_Mark: "NSM",
  Boundary_Neutral: "BN",
  Paragraph_Separator: "B",
  Segment_Separator: "S",
  White_Space: "WS",
  Other_Neutral: "ON",
  Left_To_Right_Embedding: "LRE",
  Right_To_Left_Embedding: "RLE",
  Left_To_Right_Override: "LRO",
  Right_To_Left_Override: "RLO",
  Pop_Directional_Format: "PDF",
  Left_To_Right_Isolate: "LRI",
  Right_To_Left_Isolate: "RLI",
  First_Strong_Isolate: "FSI",
  Pop_Directional_Isolate: "PDI",
};

const MODULE_PREFIX = `// Copyright 2023 Im-Beast. MIT license.
// Generated by scripts/update_unicode_bidi.ts from pinned unicode.org inputs.
// Do not edit by hand; run the network-free --check mode in CI.

/** Checked-in Unicode ${UNICODE_VERSION} UAX #9 bidi data. */
// deno-fmt-ignore
export const GENERATED_UNICODE_17_0_0_BIDI_DATA: unknown = JSON.parse(String.raw\``;
const MODULE_SUFFIX = "`);\n";

async function sha256(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function download(source: { url: string; sha256: string }): Promise<string> {
  const response = await fetch(source.url);
  if (!response.ok) throw new Error(`${source.url}: HTTP ${response.status}`);
  const text = await response.text();
  if (text.length > MAX_SOURCE_BYTES) throw new Error(`${source.url}: exceeds ${MAX_SOURCE_BYTES} bytes`);
  const digest = await sha256(text);
  if (digest !== source.sha256) {
    throw new Error(`${source.url}: unpinned content ${digest} (expected ${source.sha256})`);
  }
  return text;
}

interface Range {
  start: number;
  end: number;
  value: string;
}

function parseRanges(text: string): { explicit: Range[]; missing: Range[] } {
  const explicit: Range[] = [];
  const missing: Range[] = [];
  for (const line of text.split("\n")) {
    const missingMatch = /^# @missing: ([0-9A-F]+)\.\.([0-9A-F]+); (\w+)/.exec(line);
    if (missingMatch) {
      const value = LONG_TO_SHORT[missingMatch[3]!] ?? missingMatch[3]!;
      missing.push({ start: parseInt(missingMatch[1]!, 16), end: parseInt(missingMatch[2]!, 16), value });
      continue;
    }
    const body = line.split("#")[0]!.trim();
    if (!body) continue;
    const [codes, longValue] = body.split(";").map((part) => part.trim());
    if (!codes || !longValue) continue;
    const [startHex, endHex] = codes.split("..");
    const value = LONG_TO_SHORT[longValue] ?? longValue;
    explicit.push({ start: parseInt(startHex!, 16), end: parseInt(endHex ?? startHex!, 16), value });
  }
  explicit.sort((left, right) => left.start - right.start);
  missing.sort((left, right) => left.start - right.start);
  return { explicit, missing };
}

function mergeAdjacent(ranges: Range[]): Range[] {
  const merged: Range[] = [];
  for (const range of ranges) {
    const last = merged.at(-1);
    if (last && last.value === range.value && range.start === last.end + 1) last.end = range.end;
    else merged.push({ ...range });
  }
  return merged;
}

function encodeTriplets(ranges: Range[], values: readonly string[]): number[] {
  const out: number[] = [];
  let previousEnd = 0;
  for (const range of ranges) {
    out.push(range.start - previousEnd, range.end - range.start, values.indexOf(range.value));
    previousEnd = range.end + 1;
  }
  return out;
}

async function build(): Promise<{ moduleText: string; testText: string }> {
  const [classText, bracketText, testText] = await Promise.all([
    download(SOURCES.bidiClass),
    download(SOURCES.brackets),
    download(SOURCES.test),
  ]);
  if (!testText.startsWith(`# BidiCharacterTest-${UNICODE_VERSION}.txt`)) {
    throw new Error("BidiCharacterTest fixture version header is not pinned.");
  }

  const { explicit, missing } = parseRanges(classText);
  // Compact: drop explicit L ranges outside missing-default regions — the
  // runtime default is L there anyway. Inside a missing region, explicit L
  // must stay to override the region default.
  const inMissing = (codePoint: number): boolean =>
    missing.some((range) => range.start !== 0 && codePoint >= range.start && codePoint <= range.end);
  const kept = mergeAdjacent(
    explicit.filter((range) => range.value !== "L" || inMissing(range.start) || inMissing(range.end)),
  );
  const missingKept = mergeAdjacent(missing.filter((range) => range.start !== 0)); // the global L default is implicit

  const values = [...new Set([...kept.map((range) => range.value), ...missingKept.map((range) => range.value)])]
    .sort();

  const brackets: number[][] = [];
  for (const line of bracketText.split("\n")) {
    const body = line.split("#")[0]!.trim();
    if (!body) continue;
    const [code, paired, type] = body.split(";").map((part) => part.trim());
    if (!code || !paired || !type) continue;
    brackets.push([parseInt(code, 16), parseInt(paired, 16), type === "o" ? 0 : 1]);
  }

  const payload = {
    schema: "deno-tui.unicode-bidi-data",
    schemaVersion: 1,
    unicodeVersion: UNICODE_VERSION,
    values,
    ranges: encodeTriplets(kept, values),
    missingRanges: encodeTriplets(missingKept, values),
    brackets,
    sources: Object.fromEntries(Object.entries(SOURCES).map(([name, source]) => [name, source.sha256])),
  };
  return { moduleText: `${MODULE_PREFIX}${JSON.stringify(payload)}${MODULE_SUFFIX}`, testText };
}

async function check(): Promise<void> {
  const moduleText = await Deno.readTextFile(OUTPUT_PATH);
  const digest = await sha256(moduleText);
  if (digest !== REVIEWED_MODULE_SHA256) {
    throw new Error(`bidi module is unreviewed: ${digest} (expected ${REVIEWED_MODULE_SHA256})`);
  }
  const fixture = await Deno.readTextFile(TEST_FIXTURE_PATH);
  const fixtureDigest = await sha256(fixture);
  if (fixtureDigest !== SOURCES.test.sha256) {
    throw new Error(`BidiCharacterTest fixture drifted: ${fixtureDigest} (expected ${SOURCES.test.sha256})`);
  }
  console.log(`bidi data verified: module ${digest}`);
}

if (Deno.args.includes("--check")) {
  await check();
} else {
  const { moduleText, testText } = await build();
  await Deno.writeTextFile(OUTPUT_PATH, moduleText);
  await Deno.writeTextFile(TEST_FIXTURE_PATH, testText);
  console.log(`wrote ${OUTPUT_PATH.pathname}`);
  console.log(`module sha256: ${await sha256(moduleText)} (update REVIEWED_MODULE_SHA256)`);
}
